# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDc0NzU3OTU1ZDIxNjc2MjI1N2U5ZmYwNmE4MWMyYmNkMjU3YzIxMGUwODQ1ZjJkZGQyNzZhMTU4ZTBmMTNlYmJhYzM5NWI2OGEwY2IxM2Q4YTdiNDdiMTFlNmQ4NTFlNmFmMTEyZjU0M2Q2NWMwZDM5NzZkZGU4NTM0NGZhZDE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
